# Generated by Django 3.2.6 on 2021-08-09 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rent_cost', models.FloatField()),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='play.addresses_fields')),
            ],
        ),
        migrations.CreateModel(
            name='football_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField()),
                ('min_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field', to='play.fields')),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='masculino', max_length=50)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('dominant_food', models.CharField(blank=True, choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo')], default='derecho', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='play.matches')),
                ('players', models.ManyToManyField(related_name='players', to='play.players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='play.positions'),
        ),
        migrations.AddField(
            model_name='players',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matches',
            name='teams_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_a', to='play.teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='teams_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_b', to='play.teams'),
        ),
        migrations.AddField(
            model_name='fields',
            name='fields_services',
            field=models.ManyToManyField(related_name='fields_services', to='play.service'),
        ),
        migrations.AddField(
            model_name='fields',
            name='football_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_type', to='play.football_types'),
        ),
    ]
