# Generated by Django 3.2.6 on 2021-09-09 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import play.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='administrator',
        ),
        migrations.AddField(
            model_name='field',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='admin_default.png', upload_to=play.models.media_path, validators=[play.models.validate_media_size])),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='play.field')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
