# Generated by Django 3.2.6 on 2021-09-13 07:11

from django.db import migrations, models
import play.models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='photo',
            field=models.ImageField(blank=True, default='default_field.png', upload_to=play.models.media_path_field),
        ),
    ]
