# Generated by Django 3.2.6 on 2021-08-20 04:26

from django.db import migrations, models
import django.utils.timezone
import play.models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20210819_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfield',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='photo',
            field=models.ImageField(blank=True, default='field_default.jpg', upload_to=play.models.media_path_field),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teams', to='play.Player'),
        ),
    ]
