# Generated by Django 3.2.6 on 2021-09-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_alter_field_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(blank=True, choices=[('varonil', 'Varonil'), ('femenil', 'Femenil'), ('mixto', 'Mixto')], max_length=30),
        ),
    ]
