# Generated by Django 3.2.6 on 2021-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_match_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teammates',
            field=models.ManyToManyField(related_name='friends', to='play.Player'),
        ),
    ]
