# Generated by Django 3.2.6 on 2021-09-10 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20210909_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
