# Generated by Django 3.2.6 on 2021-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_team_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballtype',
            name='duration',
            field=models.IntegerField(default=60, max_length=10),
            preserve_default=False,
        ),
    ]
