# Generated by Django 3.2.6 on 2021-09-01 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import play.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0005_footballtype_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballtype',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('varonil', 'Varonil'), ('femenil', 'Femenil'), ('mixto', 'Mixto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='avatar_default.png', upload_to=play.models.media_path, validators=[play.models.validate_media_size]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='play.position'),
        ),
    ]
