# Generated by Django 3.2.6 on 2021-09-05 04:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
